version: '3.3'

services:
  # База данных PostgreSQL
  obed-db:
    image: postgres:16-alpine
    container_name: obed-store-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Берется из .env на сервере
      POSTGRES_DB: obed_store_db
    volumes:
      - obed_db_data:/var/lib/postgresql/data

  # Основное приложение
  obed-app:
    build: .
    container_name: obed-store-app
    restart: unless-stopped
    depends_on:
      - obed-db
    env_file:
      - .env # Автоматически передает ВСЕ переменные из .env в приложение
    volumes:
      - ./reports:/app/reports
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8282:8282"
      
    security_opt:
      - no-new-privileges:true

volumes:
  obed_db_data:
