name: Deploy to Server

on:
  push:
    branches:
      - main  # Сценарий срабатывает при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/docker/obed.store
            git pull origin main
            # Собираем и перезапускаем ТОЛЬКО сервис приложения
            docker-compose up -d --build obed-app
            # Удаляем старые ненужные образы, чтобы не забивать место
            docker image prune -f
